export const data = {
  game: "название клона",
  linkGesture: "./assets/hold/gestures/ice.webp",
  linkBackground: "./assets/hold/backgrounds/palm_scratch.webp",
  linkLike: "./assets/hold/likes/plus_green.webp",
  textTitle: "Оказание помощи",
  textGesture: "Лёд",
  textTask0: "Приложи холод к ране!",
  textTask1: "Держи!",
  textWin: "Отлично! Холод сужает сосуды и останавливает кровотечение.",
  soundRegular: "./assets/hold/sounds/blood_dripping.webm",
  soundStart: "./assets/hold/sounds/fingers.webm",
  soundTarget: "./assets/hold/sounds/ice_used.webm",
  soundWin: "./assets/hold/sounds/win.webm",
  soundLike: "./assets/hold/sounds/like.webm",
};
